import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { ShoppingCart, BookOpen} from 'lucide-react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-4`}
      >
        <div className="min-h-screen bg-background">

              <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center justify-between">
          <Link href="/user/home" className="flex items-center space-x-2">
            <BookOpen className="h-6 w-6" />
            <span className="text-xl font-bold">BookHaven</span>
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="/user/home" className="text-sm font-medium text-primary">
              Home
            </Link>
            <Link href="/user/orders" className="text-sm font-medium hover:text-primary">
              My Orders
            </Link>
            <Link href="/user/search" className="text-sm font-medium hover:text-primary">
              Search Books
            </Link>
            <Link href="/user/wishlists" className="text-sm font-medium hover:text-primary">
              Wishlists
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Button variant="ghost" size="icon">
              <ShoppingCart className="h-5 w-5" />
            </Button>
            <div className="h-8 w-8 rounded-full bg-primary" />
          </div>
        </div>
      </header>
        {children}
        </div>
      </body>
    </html>
  );
}
